INSERT INTO `instage`.`cv`
(`IdCV`,
`Resume`,
`ExperienceTravail`,
`Education`,
`Certification`,
`Competence`,
`Langue`)
VALUES
(1,
"Blabla resumé",
"Épicerie Métro",
"DEC Programmation",
"Cisco",
"Travaillant",
"Français, Anglais"),
(1,
"Blabla resumé",
"Épicerie Métro",
"DEC Programmation",
"Cisco",
"Travaillant",
"Français, Anglais"),
(1,
"Blabla resumé",
"Épicerie Métro",
"DEC Programmation",
"Cisco",
"Travaillant",
"Français, Anglais"),
(1,
"Blabla resumé",
"Épicerie Métro",
"DEC Programmation",
"Cisco",
"Travaillant",
"Français, Anglais"),
(1,
"Blabla resumé",
"Épicerie Métro",
"DEC Programmation",
"Cisco",
"Travaillant",
"Français, Anglais");